version: "3.8"
services:
  nodeserver:
    restart: always
    build:
      context: ./Backend
    ports:
      - "4000:4000"

  nginx:
    restart: always
    build:
      context: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - nodeserver
    

  
